### ISSUE TITLE
PR / Campaigns

### ISSUE THREAD

**Issue by jcstraley** [aulitech/Cato#162]
##Subtasks

- [ ] IN THE NEWS - January News (ATIA, ARM)
- [ ] Press Release 2 - AUTONOMOUS (PBS)
- [ ] PRess Release 3 - MIT CSAIL, biped.ai??
- [ ] Packaging for Giveaways (10 Pair)
- [ ] Spero on Podcast - UnitedOnWheels (United Spinal)
- [ ] eMail Campaign structure
- [ ] eMail Invitations - RESNA (Feb 27??)
- [ ] eMail Invitations - ATIA (asap - Feb 20?)
- [ ] eMail - CSUN Teaser/Calendly (March 5??)

**Comment by sperok** [comment]
Move to AULI Roadmap project
